extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tdce]
pipeline = [
    "bril2json",
    "tdce",
    "brili -p {args}",
]

[runs.tdce_plus]
pipeline = [
    "bril2json",
    "tdce+",
    "brili -p {args}",
]
